### ISSUE TITLE
Swizzles does not run in CuteChess

### ISSUE THREAD

**Issue by tissatussa** [kz04px/swizzles#8]
This happens with all binaries which i (successfully) compiled by your recent source files : Swizzles shows a few pv lines while calculating its first move, but after a few seconds CuteChess decides a loss .. it seems Swizzles crashed and/or gave some invalid output. You should certainly test and solve this !

I used just the default UCI options (Hash 1 Mb and Threads 1) and no special start FEN.
I'm on Xubuntu 21.10 and CuteChess v1.2.0

**Comment by kz04px** [comment]
Thanks for making an issue.
Would you be able to post the output from CuteChess? Ideally with -debug enabled. I haven't ran into any such issue so far myself and can't seem to replicate it yet.

**Comment by tissatussa** [comment]
I always use the CuteChess GUI but i copied the log text :

![Screenshot_2022-04-05_07-28-13](https://user-images.githubusercontent.com/1109281/161685142-1fb9ebd7-4896-4c71-9da8-0ee6eab62c02.png)

and here's the ZIPped log : [log.zip](https://github.com/kz04px/swizzles/files/8415119/log.zip)
NOTE: this is the complete log of the "game" .. we see no 'stop' command or error, but believe me, CuteChess stopped the game after 2 seconds or so, showing "0-1". I can even send you a screencast of such "game" and my compiled binary (which seems OK when doing the command 'uci' in terminal).

**Comment by tissatussa** [comment]
```
[Event "?"]
[Site "?"]
[Date "2022.04.05"]
[Round "?"]
[White "Swizzles"]
[Black "Amoeba v3.4"]
[Result "0-1"]
[GameDuration "00:00:02"]
[PlyCount "0"]
[Termination "abandoned"]
[TimeControl "480"]

{White disconnects} 0-1

```

**Comment by kz04px** [comment]
While I can't replicate this still, it might now be fixed. It'd be much appreciated if you could test this again. Thanks.

**Comment by tissatussa** [comment]
Indeed it is fixed !

> While I can't replicate this still..

Why can't you replicate this? Do you (only) use Windows? Does it only happen on Linux? I doubt it .. I just compiled your source into a Linux binary, according to your build instructions (which are common) and all went well .. adding this Swizzles version to CuteChess (GUI) it plays a decent game now !? I also tested in terminal, with basic commands 'uci' followed by 'go infinite', but i see no output at all .. do you? Other engines DO give output this way, so it's strange to me .. however, as i stated, when running this Swizzles version in the CuteChess GUI, i DO see pv-lines in the output pane .. so it works, but i don't understand why.

> ..it might now be fixed

i see you did "Fix qsearch bug : Forgot to test if a move puts/leaves us in check".
i only tested from the start position, so no check is possible then !?  Nevermind ..

**Comment by kz04px** [comment]
> Why can't you replicate this? Do you (only) use Windows? Does it only happen on Linux?

I tried using the same input as you with the same version of CuteChess on Linux Mint, and everything ran as expected. Eventually I asked someone else to try find a position it crashed in which I was able to replicate and then fix.

> I also tested in terminal, with basic commands 'uci' followed by 'go infinite', but i see no output at all .. do you?

That's likely because you didn't provide it with an `isready` before trying to start a search. At some point I might loosen this requirement.

> Indeed it is fixed !

In that case, I'll close this issue. Thanks a lot for the help.

**Comment by tissatussa** [comment]
> That's likely because you didn't provide it with an `isready` before trying to start a search.

You're right, then it works! I didn't know that .. most engines don't need this, but indeed the "Description of the universal chess interface (UCI) - April 2004" does mention it.
Btw. you write _"try find a position it crashed in"_ but that was not the case : the log just showed 'disconnects', but probably you mean the same .. nevermind, let's close the issue.
